package com.hologic.hdl.util

import java.sql.Timestamp
/**
 * This class defines CaseData dataset
 */
  /**-----------------------------------------------------------------------------------
 *This  Case object holding values for parsed from XML
 *Input 					: 
 *Output 					: 
 *project Name 		: Hologic Data Lake
 *File Name 			: AssetRecord.scala
 *Author					: Arun Srinivasan
 *Description			: AssetRecord case class  
 *Modification History	:
 *-----------------------------------------------------------------------------------
 *-----------------------------------------------------------------------------------
 *Modified by 				Date 					 		Version.No. 		Description
 *Arun Srinivasan   	July 11, 2017  			 1.0 				Initial Release
 * Chinmaya R           November 08 2017  1.1     added fields for UTC columns
 *-----------------------------------------------------------------------------------
 *-----------------------------------------------------------------------------------
 */
case class CaseRecord (
  Hologic_Id : String,
	Identification_Id: String,
	Identification_SourceObjectId: String,
	Identification_SourceParentObjectId: String,
	Identification_Number: String,
	Identification_Revision: String, 
	Identification_QueueRecordId: String,
	Identification_CommonId: String,
	OracleServiceRequestId: String,
	OracleServiceRequestNumber: String,
	CallerFirstName: String,
	CallerLastName: String,
	CallerCentralIdentity: String,
	CallerPhone: String,
	CallerPhoneExt: String,
	CallerEmail: String,
	Status: String,
	OracleServiceRequestFirstName: String,
	OracleServiceRequestLastName: String,
	OracleServiceRequestEmail: String,
	OracleServiceRequestPhoneNumber: String,
	ProblemCode: String,
	ProblemSummary: String,
	Category: String,
	SubCategory: String,
	Type: String,
	Severity: String,
	SRNumber: String,
	ReportedDate: Timestamp,
	IncidentDate: Timestamp,
	ClosedOn: Timestamp,
	InstrumentInstallDate: Timestamp,
	SROwner: String,
	AssignedTo: String,
	LoggedBy: String,
	LoggedByName: String,
	CreatedByName: String,
	SRChannel: String,
	BillToPartyName: String,
	BillToPartyNumber: String,
	BillToLocation_Identification_Id: String,
	BillToLocation_Identification_SourceObjectId: String,
	BillToLocation_Identification_SourceParentObjectId: String,
	BillToLocation_Identification_Number: String,
	BillToLocation_Identification_Revision: String,
	BillToLocation_Identification_QueueRecordId: String,
	BillToLocation_Identification_CommonId: String,
	BillToLocation_Type: String,
	BillToLocation_PartyName: String,
	BillToLocation_PartyNumber: String,
	BillToLocation_SiteNumber: String,
	BillToLocation_Location_Location_Identification_Id: String,
	BillToLocation_Location_Location_Identification_SourceObjectId: String,
	BillToLocation_Location_Location_Identification_SourceParentObjectId: String,
	BillToLocation_Location_Location_Identification_Number: String,
	BillToLocation_Location_Location_Identification_Revision: String,
	BillToLocation_Location_Location_Identification_QueueRecordId: String,
	BillToLocation_Location_Location_Identification_CommonId: String,
	BillToLocation_Location_Location_AddressLine1: String,
	BillToLocation_Location_Location_AddressLine2: String,
	BillToLocation_Location_Location_AddressLine3: String,
	BillToLocation_Location_Location_AddressLine4: String,
	BillToLocation_Location_Location_City: String,
	BillToLocation_Location_Location_County: String,
	BillToLocation_Location_Location_State: String,
	BillToLocation_Location_Location_PostalCode: String,
	BillToLocation_Location_Location_PostalCodeExt: String,
	BillToLocation_Location_Location_Country: String,
	ShipToPartyName: String,
	ShipToPartyNumber: String,
	ShipToLocation_Identification_Id: String,
	ShipToLocation_Identification_SourceObjectId: String,
	ShipToLocation_Identification_SourceParentObjectId: String,
	ShipToLocation_Identification_Number: String,
	ShipToLocation_Identification_Revision: String,
	ShipToLocation_Identification_QueueRecordId: String,
	ShipToLocation_Identification_CommonId: String,
	ShipToLocation_Type: String,
	ShipToLocation_PartyName: String,
	ShipToLocation_PartyNumber: String,
	ShipToLocation_SiteNumber: String,
	ShipToLocation_Location_Location_Identification_Id: String,
	ShipToLocation_Location_Location_Identification_SourceObjectId: String,
	ShipToLocation_Location_Location_Identification_SourceParentObjectId: String,
	ShipToLocation_Location_Location_Identification_Number: String,
	ShipToLocation_Location_Location_Identification_Revision: String,
	ShipToLocation_Location_Location_Identification_QueueRecordId: String,
	ShipToLocation_Location_Location_Identification_CommonId: String,
	ShipToLocation_Location_Location_AddressLine1: String,
	ShipToLocation_Location_Location_AddressLine2: String,
	ShipToLocation_Location_Location_AddressLine3: String,
	ShipToLocation_Location_Location_AddressLine4: String,
	ShipToLocation_Location_Location_City: String,
	ShipToLocation_Location_Location_County: String,
	ShipToLocation_Location_Location_State: String,
	ShipToLocation_Location_Location_PostalCode: String,
	ShipToLocation_Location_Location_PostalCodeExt: String,
	ShipToLocation_Location_Location_Country: String,
	InstalledAtPartyName: String,
	InstalledAtPartyNumber: String,
	InstalledAtLocation_Identification_Id: String,
	InstalledAtLocation_Identification_SourceObjectId: String,
	InstalledAtLocation_Identification_SourceParentObjectId: String,
	InstalledAtLocation_Identification_Number: String,
	InstalledAtLocation_Identification_Revision: String,
	InstalledAtLocation_Identification_QueueRecordId: String,
	InstalledAtLocation_Identification_CommonId: String,
	InstalledAtLocation_Type: String,
	InstalledAtLocation_PartyName: String,
	InstalledAtLocation_PartyNumber: String,
	InstalledAtLocation_SiteNumber: String,
	InstalledAtLocation_Location_Location_Identification_Id: String,
	InstalledAtLocation_Location_Location_Identification_SourceObjectId: String,
	InstalledAtLocation_Location_Location_Identification_SourceParentObjectId: String,
	InstalledAtLocation_Location_Location_Identification_Number: String,
	InstalledAtLocation_Location_Location_Identification_Revision: String,
	InstalledAtLocation_Location_Location_Identification_QueueRecordId: String,
	InstalledAtLocation_Location_Location_Identification_CommonId: String,
	InstalledAtLocation_Location_Location_AddressLine1: String,
	InstalledAtLocation_Location_Location_AddressLine2: String,
	InstalledAtLocation_Location_Location_AddressLine3: String,
	InstalledAtLocation_Location_Location_AddressLine4: String,
	InstalledAtLocation_Location_Location_City: String,
	InstalledAtLocation_Location_Location_County: String,
	InstalledAtLocation_Location_Location_State: String,
	InstalledAtLocation_Location_Location_PostalCode: String,
	InstalledAtLocation_Location_Location_PostalCodeExt: String,
	InstalledAtLocation_Location_Location_Country: String,
	OwnedPartyName: String,
	OwnedByPartyNumber: String,
	OwnedByLocation_Identification_Id: String,
	OwnedByLocation_Identification_SourceObjectId: String,
	OwnedByLocation_Identification_SourceParentObjectId: String,
	OwnedByLocation_Identification_Number: String,
	OwnedByLocation_Identification_Revision: String,
	OwnedByLocation_Identification_QueueRecordId: String,
	OwnedByLocation_Identification_CommonId: String,
	OwnedByLocation_Type: String,
	OwnedByLocation_PartyName: String,
	OwnedByLocation_PartyNumber: String,
	OwnedByLocation_SiteNumber: String,
	OwnedByLocation_Location_Location_Identification_Id: String,
	OwnedByLocation_Location_Location_Identification_SourceObjectId: String,
	OwnedByLocation_Location_Location_Identification_SourceParentObjectId: String,
	OwnedByLocation_Location_Location_Identification_Number: String,
	OwnedByLocation_Location_Location_Identification_Revision: String,
	OwnedByLocation_Location_Location_Identification_QueueRecordId: String,
	OwnedByLocation_Location_Location_Identification_CommonId: String,
	OwnedByLocation_Location_Location_AddressLine1: String,
	OwnedByLocation_Location_Location_AddressLine2: String,
	OwnedByLocation_Location_Location_AddressLine3: String,
	OwnedByLocation_Location_Location_AddressLine4: String,
	OwnedByLocation_Location_Location_City: String,
	OwnedByLocation_Location_Location_County: String,
	OwnedByLocation_Location_Location_State: String,
	OwnedByLocation_Location_Location_PostalCode: String,
	OwnedByLocation_Location_Location_PostalCodeExt: String,
	OwnedByLocation_Location_Location_Country: String,
	ServiceItem_ServiceItem_Identification_Id: String,
	ServiceItem_ServiceItem_Identification_SourceObjectId: String,
	ServiceItem_ServiceItem_Identification_SourceParentObjectId: String,
	ServiceItem_ServiceItem_Identification_Number: String,
	ServiceItem_ServiceItem_Identification_Revision: String,
	ServiceItem_ServiceItem_Identification_QueueRecordId: String,
	ServiceItem_ServiceItem_Identification_CommonId: String,
	ServiceItem_ServiceItem_ItemInstanceNumber: String,
	ServiceItem_ServiceItem_ItemCategory: String,
	ServiceItem_ServiceItem_SerialNumber: String,
	ServiceItem_ServiceItem_ItemDescription: String,
	ServiceItem_ServiceItem_ItemCode: String,
	ComplaintFlag: String,
	ErrorCode: String,
	Urgency: String,
	SeverityCategory: String,
	CustomerAccount_CaseCustomer_Identification_Id: String,
	CustomerAccount_CaseCustomer_Identification_SourceObjectId: String,
	CustomerAccount_CaseCustomer_Identification_SourceParentObjectId: String,
	CustomerAccount_CaseCustomer_Identification_Number: String,
	CustomerAccount_CaseCustomer_Identification_Revision: String,
	CustomerAccount_CaseCustomer_Identification_QueueRecordId: String,
	CustomerAccount_CaseCustomer_Identification_CommonId: String,
	CustomerAccount_CaseCustomer_CustomerAccountName: String,
	ContactId: String,
	EntitlementId: String,
	HasCommentsUnreadByOwner: String,
	HasSelfServiceComments: String,
	IsEscalated: String,
	EscalationLevel: String,
	IsDeleted: String,
	IsSelfServiceClosed: String,
	IsStopped: String,
	IsVisibleInSelfService: String,
	LastReferencedDate: Timestamp,
	LastViewedDate: Timestamp,
	MilestoneStatus: String,
	Origin: String,
	ParentId: String,
	Priority: String,
	QuestionId: String,
	SlaExitDate: Timestamp,
	SlaStartDate: String,
	StopStartDate: String,
	SuppliedCompany: String,
	SuppliedEmail: String,
	SuppliedName: String,
	SuppliedPhone: String,
	SystemModstamp: String,
	ContractId: String,
	ContractDocId: String,
	ContractDocNumber: String,
	ContractNumber: String,
	ContractLineId: String,
	ContractLineNumber: String,
	ServiceLineNumber: String,
	ServiceName: String,
	ResolutionCode: String,
	ResolutionSummary: String,
	UpdatedBy: String,
	UpdatedDate: Timestamp,
	PatientImpact: String,
	Investigation: String,
	OperationCodeLevel1: String,
	OperationCodeLevel2: String,
	OperationCodeLevel3: String,
	hdl_created_by : String,
	hdl_created_time : Timestamp,
	InstrumentInstallDate_UT : String,
	SlaStartDate_UT : String,
	StopStartDate_UT : String,
	UpdatedDate_UT : String,
	hdl_year : Int,
	hdl_month : Int,
	hdl_day : Int
)
